### ISSUE TITLE
[_uaf_*] Create new weapons for BG and 95 and give them optics

### ISSUE THREAD

**Issue by Ligthert** [Lowlands-Tactical/NLD_Units_OPFOR#16]
In its current state all the UAF factions don't have any optics on their weapons. We need to some custom config that does this for our units
- [x] Fort221
- [x] Fort222
- [x] Fort222 UGL
- [x] Fort401
- [x] AKS74
- [x] AKS74U
- [x] The other weapon of AR.

**Comment by ShiftySean** [comment]
done
