### ISSUE TITLE
[_uaf_*] Foutjes gevonden.

### ISSUE THREAD

**Issue by ancorb1974** [Lowlands-Tactical/NLD_Units_OPFOR#17]
95th Airmobile Brigade
- [x] Geen piloten.
- [x] Crew heft gewone helmen.
- [x] Marksman heft geen scope, wel 2 designator batterijen maar geen designator.
- [x] FAC heeft geen binoculars/rangefinder/laserdesignator.
- [x] MAT is TE ZWAAR, heeft geen stamina. 
- [x] AA is TE ZWAAR, heeft geen stamina.
- [x] Officer/TL/SL hebben geen binoculars/rangefinder/laserdesignator.
- [x] MMG heeft AK74 mags.
- [x] Het voertuigen park vind ik te magertjes, geen heli’s, geen BTR’s.

Border Guards
- [x] Geen handguns.
- [x] MATheeft  CSAT launcher.
- [x] MMG is TE ZWAAR, heeft geen stamina.
- [x] LAT is TE ZWAAR, heeft geen stamina.
- [x] Rifleman heeft geen backpack.
- [x] Het voertuigen park vind ik te magertjes, oeps er is er geen 1 ;)
- [x] Quads, vrachtwagens, BTR’s, humvees, heli’s ??

**Comment by ShiftySean** [comment]
To-do:
- [x] Kan geen granaten switchen for whatever reason
- [x] TL/SL heeft geen GL geweer
- [x] DM nog geen rangefinder/TL+SL nog geen bino
- [x] Backpack TL en SL op de schop nemen
