### ISSUE TITLE
Uniform verkeerde texture op de grond

### ISSUE THREAD

**Issue by ShiftySean** [Lowlands-Tactical/NLD_Units_OPFOR#19]
Als je het uniform van een oekraïnse op de grond sleep of verwisseld met de jouwe, zal je een AAF uniform op de grond zien liggen (inclusief 2 handjes Oo)

**Comment by Ligthert** [comment]
We kunnen het neerzetten als een known issue. Want als de CV90 aan het fikken is, dan zie je ook nog gewoon de AAF texture erop zitten.

**Comment by ShiftySean** [comment]
fixed
