### ISSUE TITLE
Motorized Team

### ISSUE THREAD

**Issue by ancorb1974** [Lowlands-Tactical/NLD_Units_OPFOR#21]
deze groep heeft 8 infanterie buiten de auto's, en 4 in de auto's
In de auto's is er plaats voor 8....
Maar er zitten een bestuurder en een commander in elk voertuig dus heb je maar plaats voor 2 in elk voertuig, dus plaats voor 4 totaal.

oplossing is de noirmale nemen en 2 uit je team gooien want de bestuurders gelden ook als teamleden heb je er nog 8 in je team en iedereen past in de voertuigen :)

**Comment by ShiftySean** [comment]
fixed
