### ISSUE TITLE
classes for full ghilliesuits

### ISSUE THREAD

**Issue by ancorb1974** [Lowlands-Tactical/NLD_Units_OPFOR#22]
Er zijn 3 soorten full ghilliesuits met het enige verschil tussen de 3 factions de voorkant.
Ik heb als eerste een sniper aangemaakt in de config, jullie kunnen het vanaf hier wel overnemen.
Hij komt onder Men (Special Forces) te staan
BLUFOR:
B_ghillie_lsh_F
B_ghillie_sard_F
B_ghillie_ard_F

OPFOR:
O_ghillie_lsh_F
O_ghillie_sard_F
O_ghillie_ard_F

INDFOR:
I_ghillie_lsh_F
I_ghillie_sard_F
I_ghillie_ard_F

Smootch

**Comment by ShiftySean** [comment]
danku, zijn toegevoegd :)
