### ISSUE TITLE
Russen hebben geen helmen.

### ISSUE THREAD

**Issue by Ligthert** [Lowlands-Tactical/NLD_Units_OPFOR#26]
Je krijgt deze error op het scherm:
`Warning Message: Cannot open object sp_pack\models\ssh68helmet2.p3d`

En alle NLD Units OPFOR russen zien er zo uit: http://i.imgur.com/KEoLOkO.jpg

Ukrainers zijn ok.

**Comment by ancorb1974** [comment]
Is gefixt 30 juli 2016.
Gemarkeerd met Belangrijke UPDATE. nooit iets mee gebeurd.

https://github.com/Lowlands-Tactical/NLD_Units_OPFOR/commit/d9adaefe4d4d1f5942ca5bf37b33781760d103a3
