### ISSUE TITLE
[_ru_vdv*] VDV bewapening

### ISSUE THREAD

**Issue by Edzardo** [Lowlands-Tactical/NLD_Units_OPFOR#4]
De RPK is een verouderd wapen en is volgens mij zo goed als uitgefaseerd bij de VDV. Ze gekbruiken nu voornamelijk pkm en pecheneg.

**Comment by ShiftySean** [comment]
Zowel de RPK als PKM worden uitgefaseerd door de PKP (maar ze zijn er nog wel hier en daar). Denk dat gewoon een Automatic rifleman met RPK en een mmger met PKP goed is en mssn standaard in groepen een mmger laat meelopen ipv een automatic rifleman. Dan zit het er wel in evt, maar zal minder aanwezig zijn.

**Comment by ShiftySean** [comment]
Nog even verderbouwend hierop. Heb van het weekend een lijst gemaakt van zowel VDV als Oekraïnse bewapening en uitrusting, classnames and all.
Dus wat ik in gedachte heb voor de VDV
Ak74m (+GP25 ugl) Kobra sight
AKS-74U (voor bemanningen)
RPK74M (AR) Kobra sight
PKP Pecheneg (MMG)
SVD Dragunov (sniper) pso-3 scope
MP-443 Grach (vanilla "Rook" pistol)
Igla anti-air missile
Metis Heavy anti-tank
RPG-32 medium anti-tank
